In [1]:
import pandas as pd

df = pd.read_csv("data/e-commerce_stream/2019-Dec.csv")
df.head()

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-12-01 00:00:00 UTC,view,1005105,2232732093077520756,construction.tools.light,apple,1302.48,556695836,ca5eefc5-11f9-450c-91ed-380285a0bc80
1,2019-12-01 00:00:00 UTC,view,22700068,2232732091643068746,NaN,force,102.96,577702456,de33debe-c7bf-44e8-8a12-3bf8421f842a
2,2019-12-01 00:00:01 UTC,view,2402273,2232732100769874463,appliances.personal.massager,bosch,313.52,539453785,5ee185a7-0689-4a33-923d-ba0130929a76
3,2019-12-01 00:00:02 UTC,purchase,26400248,2053013553056579841,computers.peripherals.printer,NaN,132.31,535135317,61792a26-672f-4e61-9832-7b63bb1714db
4,2019-12-01 00:00:02 UTC,view,20100164,2232732110089618156,apparel.trousers,nika,101.68,517987650,906c6ca8-ff5c-419a-bde9-967ba8e2233e

In [2]:
df.shape

(67542878, 9)

In [5]:
df.product_id.nunique()

205230

In [6]:
df.category_id.nunique()

1162

In [7]:
df.user_id.nunique()

4577232

In [8]:
df.event_type.value_counts()

event_type
view        62986067
cart         3394763
purchase     1162048
Name: count, dtype: int64

In [2]:
res = df[['product_id', 'category_id', 'category_code', 'brand']]

In [4]:
res.to_csv("data/products_original.csv", index=False)

In [8]:
import pandas as pd

prod_orig = pd.read_csv("data/products_original.csv")
prod_orig.head()

   product_id          category_id                  category_code  brand
0     1005105  2232732093077520756       construction.tools.light  apple
1    22700068  2232732091643068746                            NaN  force
2     2402273  2232732100769874463   appliances.personal.massager  bosch
3    26400248  2053013553056579841  computers.peripherals.printer    NaN
4    20100164  2232732110089618156               apparel.trousers   nika

In [8]:
categories = prod_orig[['category_id', 'category_code']].drop_duplicates().reset_index(drop=True)

In [9]:
categories.head()

           category_id                  category_code
0  2232732093077520756       construction.tools.light
1  2232732091643068746                            NaN
2  2232732100769874463   appliances.personal.massager
3  2053013553056579841  computers.peripherals.printer
4  2232732110089618156               apparel.trousers

In [10]:
categories.shape

(1162, 2)

In [18]:
categories.to_csv("data/categories.csv", index=False)

In [9]:
import pandas as pd

cat_with_names = pd.read_csv("data/categories_with_names.csv")
cat_with_names.head()

           category_id                  category_code      category_name
0  2232732093077520756       construction.tools.light        work lights
1  2232732091643068746                            NaN  fishing equipment
2  2232732100769874463   appliances.personal.massager          massagers
3  2053013553056579841  computers.peripherals.printer           printers
4  2232732110089618156               apparel.trousers           trousers

In [10]:
prod_with_cat_names = prod_orig.join(
    cat_with_names.set_index('category_id')[['category_name']],
    on='category_id',
    how='left'
)
prod_with_cat_names.head()

,product_id,category_id,category_code,brand,category_name
0,1005105,2232732093077520756,construction.tools.light,apple,work lights
1,22700068,2232732091643068746,NaN,force,fishing equipment
2,2402273,2232732100769874463,appliances.personal.massager,bosch,massagers
3,26400248,2053013553056579841,computers.peripherals.printer,NaN,printers
4,20100164,2232732110089618156,apparel.trousers,nika,trousers

In [40]:
prods = prod_with_cat_names.drop_duplicates('product_id').sort_values('product_id').reset_index(drop=True)[['product_id','category_code', 'category_name']]
prods.head()

   product_id                     category_code  category_name
0     1000544            electronics.smartphone    smartphones
1     1000894            electronics.smartphone    smartphones
2     1000978  appliances.kitchen.refrigerators  refrigerators
3     1001588          construction.tools.light    work lights
4     1001605            electronics.smartphone    smartphones

In [41]:
prods.shape

(205230, 3)

In [42]:
prods.to_csv("data/products_with_category_names.csv", index=False)

In [6]:
prods_with_names = pd.read_csv("data/products_with_product_names.csv")
prods_with_names.head()

,product_id,category_code,category_name,product_name
0,1000544,electronics.smartphone,smartphones,smartphones Model 1
1,1000894,electronics.smartphone,smartphones,smartphones Model 2
2,1000978,appliances.kitchen.refrigerators,refrigerators,refrigerators Model 3
3,1001588,construction.tools.light,work lights,work lights Model 4
4,1001605,electronics.smartphone,smartphones,smartphones Model 5

In [11]:
prod_with_prod_names = prod_with_cat_names.join(
    prods_with_names.set_index('product_id')[['product_name']],
    on='product_id',
    how='left'
)
prod_with_prod_names.head()

,product_id,category_id,category_code,brand,category_name,product_name
0,1005105,2232732093077520756,construction.tools.light,apple,work lights,work lights Model 1178
1,22700068,2232732091643068746,NaN,force,fishing equipment,fishing equipment Model 101268
2,2402273,2232732100769874463,appliances.personal.massager,bosch,massagers,massagers Model 6303
3,26400248,2053013553056579841,computers.peripherals.printer,NaN,printers,printers Model 125911
4,20100164,2232732110089618156,apparel.trousers,nika,trousers,trousers Model 90435

In [12]:
prod_with_prod_names[['product_id', 'product_name', 'category_id', 'category_name', 'category_code', 'brand']].drop_duplicates('product_id').reset_index(drop=True).to_csv("data/products.csv", index=False)

In [13]:
products = pd.read_csv("data/products.csv")
products.head()

,product_id,product_name,category_id,category_name,category_code,brand
0,1005105,work lights Model 1178,2232732093077520756,work lights,construction.tools.light,apple
1,22700068,fishing equipment Model 101268,2232732091643068746,fishing equipment,NaN,force
2,2402273,massagers Model 6303,2232732100769874463,massagers,appliances.personal.massager,bosch
3,26400248,printers Model 125911,2053013553056579841,printers,computers.peripherals.printer,NaN
4,20100164,trousers Model 90435,2232732110089618156,trousers,apparel.trousers,nika

In [5]:
users = pd.read_csv("data/users_original.csv")
users.head()

,Name,Surname,Birth Date,ID Number,PESEL,City,Postal Code,Street Name,House Number
0,LENA,WITKOWSKA,1987-02-08,JZQ077116,87020827873,Oława,55-201,ul. E. Orzeszkowej,69/132
1,MARTYNA,WROŃSKA,1974-05-26,NZL415153,74052694410,Rzeszów,35-202,ul. Leona Staniszewskiego,68
2,KINGA,DUDEK,1973-02-19,LVM049964,73021924671,Warszawa/Wesoła,05-075,ul. Malinowa,50
3,PAWEŁ,SZYMCZAK,1999-06-30,LNM993793,99063054129,Warszawa,02-937,ul. Rumiankowa,31/149
4,DAVYD,JANIK,1976-11-28,DYO250343,76112863288,Rzeszów,35-111,ul. Poprzeczna,23

In [6]:
users_main = users[['Name', 'Surname', 'Birth Date', 'City', 'Postal Code', 'Street Name', 'House Number']].rename(columns={'Name': 'name', 'Surname': 'surname', 'Birth Date': 'birth_date', 'City': 'city', 'Postal Code': 'zip_code', 'Street Name': 'street_name', 'House Number': 'house_number'}, inplace=False)
users_main.head()

,name,surname,birth_date,city,zip_code,street_name,house_number
0,LENA,WITKOWSKA,1987-02-08,Oława,55-201,ul. E. Orzeszkowej,69/132
1,MARTYNA,WROŃSKA,1974-05-26,Rzeszów,35-202,ul. Leona Staniszewskiego,68
2,KINGA,DUDEK,1973-02-19,Warszawa/Wesoła,05-075,ul. Malinowa,50
3,PAWEŁ,SZYMCZAK,1999-06-30,Warszawa,02-937,ul. Rumiankowa,31/149
4,DAVYD,JANIK,1976-11-28,Rzeszów,35-111,ul. Poprzeczna,23

In [8]:
user_ids = df['user_id'].unique()
user_ids.shape

(4577232,)

In [7]:
users_main['user_id'] = user_ids
users_main.head()

ValueError: Length of values (4577232) does not match length of index (1000000)